# SPDX-License-Identifier: Apache-2.0

config:
  cwd: './external'
  build_dir: './build/rv-virt/smoke'

product:
  name: "rv-virt-smoke"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      line_buffered: true
      exec_path: 'qemu-system-riscv32'
      exec_args: '-semihosting -M virt,aclint=on -cpu rv32 -smp 1
                 -bios none -nographic'
      defconfig: '../../boards/risc-v/qemu-rv/rv-virt/configs/smoke'
