# SPDX-License-Identifier: Apache-2.0

config:
  cwd: './external'
  build_dir: './build/rv-virt/ip-pair'

product0:
  name: "rv-virt-node0"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      boot_timeout: 30
      line_buffered: true
      exec_path: 'qemu-system-riscv32'
      exec_args: '-semihosting -M virt,aclint=on -cpu rv32 -smp 1
                  -bios none -nographic
                  -global virtio-mmio.force-legacy=false
                  -netdev tap,id=n0,ifname=tl-tap0,script=no,downscript=no
                  -device virtio-net-device,netdev=n0,mac=52:54:00:2a:00:10'
      defconfig: '../../boards/risc-v/qemu-rv/rv-virt/configs/ip-pair'
      kv:
        CONFIG_NETINIT_IPADDR: "0x0a2a000a"

product1:
  name: "rv-virt-node1"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      boot_timeout: 30
      line_buffered: true
      exec_path: 'qemu-system-riscv32'
      exec_args: '-semihosting -M virt,aclint=on -cpu rv32 -smp 1
                  -bios none -nographic
                  -global virtio-mmio.force-legacy=false
                  -netdev tap,id=n1,ifname=tl-tap1,script=no,downscript=no
                  -device virtio-net-device,netdev=n1,mac=52:54:00:2a:00:11'
      defconfig: '../../boards/risc-v/qemu-rv/rv-virt/configs/ip-pair'
      kv:
        CONFIG_NETINIT_IPADDR: "0x0a2a000b"
