# SPDX-License-Identifier: Apache-2.0

config:
  cwd: './external'
  build_dir: './build/sim/smoke'

product:
  name: "sim-smoke"
  cores:
    core0:
      name: 'main'
      device: 'sim'
      line_buffered: true
      defconfig: '../../boards/sim/sim/sim/configs/smoke'
