# SPDX-License-Identifier: Apache-2.0

config:
  cwd: './external'
  build_dir: './build/sim/ip-pair'

product0:
  name: "sim-node0"
  cores:
    core0:
      name: 'main'
      device: 'sim'
      line_buffered: true
      defconfig: '../../boards/sim/sim/sim/configs/ip-pair-node0'

product1:
  name: "sim-node1"
  cores:
    core0:
      name: 'main'
      device: 'sim'
      line_buffered: true
      defconfig: '../../boards/sim/sim/sim/configs/ip-pair-node1'
