# SPDX-License-Identifier: Apache-2.0

config:
  cwd: './external'
  build_dir: './build/sim/ip-pair'
  kv:
    CONFIG_DEBUG_SYMBOLS: "y"
    CONFIG_TESTLAB_NETTL: "y"
    CONFIG_TESTLAB_NETTL_BUFSIZE: 1024
    CONFIG_SYSTEM_PING: "y"
    CONFIG_NET_SOCKOPTS: "y"
    CONFIG_NET_TCP_WRITE_BUFFERS: "y"
    CONFIG_NET_UDP_WRITE_BUFFERS: "y"
    CONFIG_IOB_NBUFFERS: 256
    CONFIG_NET_TCP_PREALLOC_CONNS: 16
    CONFIG_NET_UDP_PREALLOC_CONNS: 16
    CONFIG_NETINIT_DRIPADDR: "0x0a2a0001"
    CONFIG_SIM_NETDEV_TAP: "y"
    CONFIG_SIM_NET_HOST_ROUTE: "n"
    CONFIG_SIM_NET_BRIDGE: "y"
    CONFIG_SIM_NET_BRIDGE_DEVICE: '"tl-br0"'
    CONFIG_DEBUG_NET: "n"
    CONFIG_DEBUG_NET_ERROR: "n"
    CONFIG_EXAMPLES_TCPBLASTER: "n"
    CONFIG_NETINIT_NETLOCAL: "n"

product0:
  name: "sim-node0"
  cores:
    core0:
      name: 'main'
      device: 'sim'
      line_buffered: true
      defconfig: 'boards/sim/sim/sim/configs/tcpblaster'
      kv:
        CONFIG_NETINIT_IPADDR: "0x0a2a000a"
        CONFIG_NETINIT_NOMAC: "y"
        CONFIG_NETINIT_SWMAC: "y"
        CONFIG_NETINIT_MACADDR_1: "0x002a0010"
        CONFIG_NETINIT_MACADDR_2: "0x5254"

product1:
  name: "sim-node1"
  cores:
    core0:
      name: 'main'
      device: 'sim'
      line_buffered: true
      defconfig: 'boards/sim/sim/sim/configs/tcpblaster'
      kv:
        CONFIG_NETINIT_IPADDR: "0x0a2a000b"
        CONFIG_NETINIT_NOMAC: "y"
        CONFIG_NETINIT_SWMAC: "y"
        CONFIG_NETINIT_MACADDR_1: "0x002a0011"
        CONFIG_NETINIT_MACADDR_2: "0x5254"
