# SPDX-License-Identifier: Apache-2.0

config:
  cwd: './external'
  build_dir: './build/qemu-intel64/smoke'

product:
  name: "qemu-intel64-smoke"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      exec_path: 'qemu-system-x86_64'
      exec_args: '-m 1G -cpu host -enable-kvm -nographic -serial mon:stdio'
      defconfig: '../../boards/x86_64/qemu/qemu-intel64/configs/smoke'
