# SPDX-License-Identifier: Apache-2.0

config:
  cwd: './external'
  build_dir: './build/qemu-intel64/can-char'

product0:
  name: "intel64-node0"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      boot_timeout: 30
      exec_path: 'qemu-system-x86_64'
      exec_args: '-m 2G -smp 4 -cpu host,+invtsc,vmware-cpuid-freq=on -enable-kvm -nographic
                  -serial mon:stdio
                  -object can-bus,id=canbus0
                  -object can-host-socketcan,id=canhost0,if=can0,canbus=canbus0
                  -object can-bus,id=canbus1
                  -device ctucan_pci,canbus0=canbus0,canbus1=canbus1'
      defconfig: '../../boards/x86_64/qemu/qemu-intel64/configs/can-char-ctucanfd'

product1:
  name: "intel64-node1"
  cores:
    core0:
      name: 'main'
      device: 'qemu'
      boot_timeout: 30
      exec_path: 'qemu-system-x86_64'
      exec_args: '-m 2G -smp 4 -cpu host,+invtsc,vmware-cpuid-freq=on -enable-kvm -nographic
                  -serial mon:stdio
                  -object can-bus,id=canbus0
                  -object can-host-socketcan,id=canhost0,if=can0,canbus=canbus0
                  -device kvaser_pci,canbus=canbus0'
      defconfig: '../../boards/x86_64/qemu/qemu-intel64/configs/can-char-kvaser'
